# circleci does not support version 3.3 ~
version: "3.2"
services:
  app:
    container_name: "oilking"
    environment:
      - BITFLYER_API_KEY
      - BITFLYER_API_SECRET
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    build:
        context: "./app"
        dockerfile: "Dockerfile"
    ports:
      - "8083:8083"
    restart: always
