FROM golang:1.17.0-alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache libc-dev gcc git openssh openssl bash && \
    go get -u golang.org/x/lint/golint

WORKDIR /go/src/oilking

COPY . .

ENV GOOS=linux
ENV GOARCH=amd64

RUN go build -o app

CMD ["./app"]